"""add db_type to connections

Revision ID: 5b23a2122f6d
Revises: c01c5c7be3fe
Create Date: 2026-08-14 23:08:38.726648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b23a2122f6d'
down_revision: Union[str, Sequence[str], None] = 'c01c5c7be3fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('db_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def upgrade() -> None:
    # Add the column as nullable first, backfill existing rows, then enforce NOT NULL --
    # adding a NOT NULL column directly fails on a table with existing rows, since
    # Postgres has nothing to put in it for them.
    op.add_column('connections', sa.Column('db_type', sa.String(), nullable=True))
    op.execute("UPDATE connections SET db_type = 'postgres' WHERE db_type IS NULL;")
    op.alter_column('connections', 'db_type', nullable=False)