"""add folders table and connection folder_id

Revision ID: c01c5c7be3fe
Revises: f8e9e6a61d94
Create Date: 2026-08-14 00:19:04.655823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c01c5c7be3fe'
down_revision: Union[str, Sequence[str], None] = 'f8e9e6a61d94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_folders_parent_id'), 'folders', ['parent_id'], unique=False)
    op.create_index(op.f('ix_folders_workspace_id'), 'folders', ['workspace_id'], unique=False)
    op.add_column('connections', sa.Column('folder_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_connections_folder_id'), 'connections', ['folder_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connections_folder_id'), table_name='connections')
    op.drop_column('connections', 'folder_id')
    op.drop_index(op.f('ix_folders_workspace_id'), table_name='folders')
    op.drop_index(op.f('ix_folders_parent_id'), table_name='folders')
    op.drop_table('folders')
    # ### end Alembic commands ###
