"""add workspaces and workspace_id

Revision ID: ed51af9b8ee8
Revises: c8df90ba2ace
Create Date: 2026-08-09 22:42:17.328557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed51af9b8ee8'
down_revision: Union[str, Sequence[str], None] = 'c8df90ba2ace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_members',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('joined_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_members_workspace_id'), 'workspace_members', ['workspace_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('chats', sa.Column('workspace_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_chats_workspace_id'), 'chats', ['workspace_id'], unique=False)
    op.add_column('connections', sa.Column('workspace_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_connections_workspace_id'), 'connections', ['workspace_id'], unique=False)
    # ### end Alembic commands ###

    # --- Data backfill: give every existing user a personal workspace,
    # and move their existing connections/chats into it ---
    import uuid
    import datetime
    from sqlalchemy import table, column, String
    from sqlalchemy.sql import select

    conn = op.get_bind()

    users_table = table("users", column("id", String))
    existing_users = conn.execute(select(users_table.c.id)).fetchall()

    for (user_id,) in existing_users:
        workspace_id = str(uuid.uuid4())
        now = datetime.datetime.utcnow().isoformat()

        conn.execute(
            table(
                "workspaces",
                column("id", String), column("name", String), column("type", String),
                column("owner_id", String), column("created_at", String),
            ).insert().values(
                id=workspace_id, name="Personal", type="personal",
                owner_id=user_id, created_at=now,
            )
        )
        conn.execute(
            table(
                "workspace_members",
                column("id", String), column("workspace_id", String),
                column("user_id", String), column("role", String), column("joined_at", String),
            ).insert().values(
                id=str(uuid.uuid4()), workspace_id=workspace_id,
                user_id=user_id, role="owner", joined_at=now,
            )
        )
        conn.execute(
            table("connections", column("workspace_id", String), column("user_id", String))
            .update().where(column("user_id") == user_id).values(workspace_id=workspace_id)
        )
        conn.execute(
            table("chats", column("workspace_id", String), column("user_id", String))
            .update().where(column("user_id") == user_id).values(workspace_id=workspace_id)
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connections_workspace_id'), table_name='connections')
    op.drop_column('connections', 'workspace_id')
    op.drop_index(op.f('ix_chats_workspace_id'), table_name='chats')
    op.drop_column('chats', 'workspace_id')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_workspace_members_workspace_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_user_id'), table_name='workspace_members')
    op.drop_table('workspace_members')
    # ### end Alembic commands ###