"""add saved_queries table

Revision ID: f8e9e6a61d94
Revises: ed51af9b8ee8
Create Date: 2026-08-11 06:47:37.800320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8e9e6a61d94'
down_revision: Union[str, Sequence[str], None] = 'ed51af9b8ee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_queries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('connection_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('sql', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_queries_connection_id'), 'saved_queries', ['connection_id'], unique=False)
    op.create_index(op.f('ix_saved_queries_user_id'), 'saved_queries', ['user_id'], unique=False)
    op.create_index(op.f('ix_saved_queries_workspace_id'), 'saved_queries', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_queries_workspace_id'), table_name='saved_queries')
    op.drop_index(op.f('ix_saved_queries_user_id'), table_name='saved_queries')
    op.drop_index(op.f('ix_saved_queries_connection_id'), table_name='saved_queries')
    op.drop_table('saved_queries')
    # ### end Alembic commands ###
